name: "Build"

on:
  pull_request:
  push: # Do not rely on `push` for PR CI - see https://github.com/guardian/mobile-apps-api/pull/2760
    branches:
      - main # Optimal for GHA workflow caching - see https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows#restrictions-for-accessing-a-cache

permissions:
  id-token: write
  contents: read
  pull-requests: write # Required for riff-raff action

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: "${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: corepack enable

      - uses: actions/setup-node@v4
        with:
          cache: yarn
          node-version-file: .nvmrc
      - uses: actions/setup-java@v4
        with:
          distribution: corretto
          cache: sbt
          java-version: 11

      - run: make reinstall
      - run: make validate
      - run: make test
      - run: make compile

      - name: Test, compile
        # Australia/Sydney  -because it is too easy for devs to forget about timezones
        run: |
          java \
          -Xmx6144M \
          -XX:ReservedCodeCacheSize=128m \
          -Dsbt.log.noformat=true \
          -XX:+UseParallelGC \
          -DAPP_SECRET="fake_secret" \
          -Duser.timezone=Australia/Sydney \
          -jar ./bin/sbt-launch.jar clean compile assets scalafmtCheckAll test Universal/packageBin Debian/packageBin

      - name: Test Summary
        uses: test-summary/action@v2
        with:
          paths: "test-results/**/TEST-*.xml"
        if: always()

      - uses: guardian/actions-riff-raff@v4.1.2
        env:
          GU_RIFF_RAFF_ROLE_ARN: ${{ secrets.GU_RIFF_RAFF_ROLE_ARN }}
        if: ${{ env.GU_RIFF_RAFF_ROLE_ARN }}
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          roleArn: ${{ secrets.GU_RIFF_RAFF_ROLE_ARN }}
          projectName: dotcom:frontend-all
          configPath: riff-raff.yaml
          contentDirectories: |
            frontend-static:
              - static/hash
            admin:
              - admin/target/universal/admin.zip
              - admin/target/admin.1.0-SNAPSHOT_all.deb
            applications:
              - applications/target/universal/applications.zip
              - applications/target/applications.1.0-SNAPSHOT_all.deb
            archive:
              - archive/target/universal/archive.zip
              - archive/target/archive.1.0-SNAPSHOT_all.deb
            article:
              - article/target/universal/article.zip
              - article/target/article.1.0-SNAPSHOT_all.deb
            commercial:
              - commercial/target/universal/commercial.zip
              - commercial/target/commercial.1.0-SNAPSHOT_all.deb
            discussion:
              - discussion/target/universal/discussion.zip
              - discussion/target/discussion.1.0-SNAPSHOT_all.deb
            facia:
              - facia/target/universal/facia.zip
              - facia/target/facia.1.0-SNAPSHOT_all.deb
            facia-press:
              - facia-press/target/universal/facia-press.zip
              - facia-press/target/facia-press.1.0-SNAPSHOT_all.deb
            identity:
              - identity/target/universal/identity.zip
              - identity/target/identity.1.0-SNAPSHOT_all.deb
            onward:
              - onward/target/universal/onward.zip
              - onward/target/onward.1.0-SNAPSHOT_all.deb
            preview:
              - preview/target/universal/preview.zip
              - preview/target/preview.1.0-SNAPSHOT_all.deb
            rss:
              - rss/target/universal/rss.zip
              - rss/target/rss.1.0-SNAPSHOT_all.deb
            sport:
              - sport/target/universal/sport.zip
              - sport/target/sport.1.0-SNAPSHOT_all.deb
