name: Commercial E2E Tests
on:
    pull_request:
        paths:
            - static/src/javascripts/projects/common/modules/commercial/**
            - static/src/javascripts/projects/commercial/**
            - static/src/javascripts/projects/common/modules/spacefinder-*
            - commercial/**
            - cypress/**
            - cypress.config.ts
            - .github/workflows/commercial-e2e.yml

concurrency:
    group: 'commercial-e2e-${{ github.head_ref }}'
    cancel-in-progress: true

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            # DCR
            - name: Checkout DCR
              uses: actions/checkout@v3
              with:
                  repository: guardian/dotcom-rendering
                  path: ./dcr

            - name: Setup DCR node
              uses: actions/setup-node@v3
              with:
                  node-version-file: './dcr/.nvmrc'

            - name: Install DCR dependencies
              uses: bahmutov/npm-install@v1
              with:
                  working-directory: ./dcr
                  install-command: yarn --frozen-lockfile --silent --ignore-scripts

            - name: Build DCR
              run: make build
              working-directory: ./dcr/dotcom-rendering

            # Frontend
            - name: Checkout frontend
              uses: actions/checkout@v3
              with:
                  path: ./frontend

            - name: Setup frontend node
              uses: actions/setup-node@v3
              with:
                  node-version-file: './frontend/.nvmrc'

            - name: Install Frontend dependencies
              uses: bahmutov/npm-install@v1
              with:
                  working-directory: ./frontend
                  cache: yarn
                  install-command: yarn --frozen-lockfile --silent --ignore-scripts
              env:
                  CYPRESS_INSTALL_BINARY: 0

            - name: Build Frontend
              run: make commercial-compile-dev
              working-directory: ./frontend

            - name: Upload build
              uses: actions/upload-artifact@v2
              with:
                  name: build
                  path: |
                      ./dcr/dotcom-rendering/dist
                      ./frontend/static/target
    e2e:
        name: E2E Tests
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                # run copies of the current job in parallel
                containers: [1, 2, 3]
        steps:
            # DCR
            - name: Checkout DCR
              uses: actions/checkout@v3
              with:
                  repository: guardian/dotcom-rendering
                  path: ./dcr

            - name: Setup DCR node
              uses: actions/setup-node@v3
              with:
                  node-version-file: './dcr/.nvmrc'

            - name: Install DCR dependencies
              uses: bahmutov/npm-install@v1
              with:
                  working-directory: ./dcr
                  install-command: yarn --frozen-lockfile --silent --ignore-scripts

            # Frontend
            - name: Checkout frontend
              uses: actions/checkout@v3
              with:
                  path: ./frontend

            - name: Setup frontend node
              uses: actions/setup-node@v3
              with:
                  node-version-file: './frontend/.nvmrc'

            - name: Download build
              uses: actions/download-artifact@v2
              with:
                  name: build

            - name: Cache Cypress
              id: cache-cypress
              uses: actions/cache@v1
              with:
                  path: ~/.cache/Cypress
                  key: cypress-cache-v2-${{ runner.os }}-${{ hashFiles('**/package.json') }}

            - run: yarn install http-server
            - run: yarn cypress install

            - name: Run Cypress
              uses: cypress-io/github-action@v5.0.2
              with:
                  install: false
                  start: make -C ../dcr/dotcom-rendering start-ci, make commercial-serve
                  working-directory: frontend
                  wait-on: 'http://localhost:3030, http://localhost:3031/graun.standalone.commercial.js'
                  wait-on-timeout: 30
                  command: yarn cy2 run --parallel --record --key 'Commercial E2E Tests' --ci-build-id '${{ github.sha }}-${{ github.workflow }}-${{ github.event_name }}' --spec cypress/e2e/**/*
              env:
                  PORT: 3030
                  COMMERCIAL_BUNDLE_URL: http://localhost:3031/graun.standalone.commercial.js
                  CYPRESS_API_URL: https://sorry-cypress.code.dev-gutools.co.uk

            - uses: actions/upload-artifact@v2
              if: failure()
              with:
                  name: cypress-screenshots
                  path: frontend/cypress/screenshots
